In [507]:
import numpy as np

In [508]:
# 1D Array

a = np.array([1,2,3])
print(a)

[1 2 3]


In [509]:
# 2D Array

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [510]:
# 3D Array

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [511]:
# dtype 

a = np.array([1, 2, 3], dtype=float)
print(a)

[1. 2. 3.]


In [512]:
# np.arange

b = np.arange(1, 9)
print(b)

[1 2 3 4 5 6 7 8]


In [513]:
# np.reshape

c = b.reshape(2, 2, 2)
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [514]:
# np.ones

a = np.ones((3,4), dtype=float)
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [515]:
# np.zeros

b = np.zeros((4,3), dtype=float)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [516]:
# np.random

c = np.random.random((3, 4))
print(c)

[[0.40802175 0.89010476 0.09223654 0.79171723]
 [0.61844308 0.95169093 0.19028381 0.91885381]
 [0.53229961 0.8761388  0.96092253 0.91472664]]


In [517]:
# np.linspace

d = np.linspace(0,10,10, dtype=int)
print(d)

[ 0  1  2  3  4  5  6  7  8 10]


In [518]:
# np.identity

d = np.identity(3, dtype=int)
print(d)
#------------OR--------------
d = np.eye(3, dtype=int)
print(d)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [519]:
# NumPy Attributes

a1 = np.arange(1, 11)
a2 = np.arange(1, 17, dtype=float).reshape(4, 4)
a3 = np.arange(1, 17, dtype=int).reshape(2, 2, 2, 2)

In [520]:
print("<-----A1----->")
print(a1)
print("\n<-----A2----->")
print(a2)
print("\n<-----A3----->")
print(a3)

<-----A1----->
[ 1  2  3  4  5  6  7  8  9 10]

<-----A2----->
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

<-----A3----->
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


In [521]:
# obj.ndim

print(f"Dimensions of a1: {a1.ndim}")
print(f"Dimensions of a2: {a2.ndim}")
print(f"Dimensions of a3: {a3.ndim}")

Dimensions of a1: 1
Dimensions of a2: 2
Dimensions of a3: 4


In [522]:
# obj.shape

print(f"Shape of a1: {a1.shape}")
print(f"Shape of a2: {a2.shape}")
print(f"Shape of a3: {a3.shape}")

Shape of a1: (10,)
Shape of a2: (4, 4)
Shape of a3: (2, 2, 2, 2)


In [523]:
# obj.size --------> tells total no: of elements of array (multiplication of shape parameters --> 2,3 -> 6)

print(f"Size of a1: {a1.size}")
print(f"Size of a2: {a2.size}")
print(f"Size of a3: {a3.size}")

Size of a1: 10
Size of a2: 16
Size of a3: 16


In [524]:
# obj.itemsize -----> tells memory size in bytes of single element of array

print(f"ItemSize of a1: {a1.itemsize}")
print(f"ItemSize of a2: {a2.itemsize}")
print(f"ItemSize of a3: {a3.itemsize}")

ItemSize of a1: 8
ItemSize of a2: 8
ItemSize of a3: 8


In [525]:
# obj.dtype

print(f"Data Type of a1: {a1.dtype}")
print(f"Data Type of a2: {a2.dtype}")
print(f"Data Type of a3: {a3.dtype}")

Data Type of a1: int64
Data Type of a2: float64
Data Type of a3: int64


In [526]:
# astype

print(a1.dtype)
print(a1.astype(np.int32).dtype)

int64
int32


In [527]:
# Array Operations

a1 = np.arange(1, 13, dtype=int).reshape(3, 4)
a2 = np.arange(13, 25, dtype=int).reshape(3,4)
a3 = np.arange(1, 13, 2, dtype=int).reshape(2, 3)

print(a1)
print()

print(a2)
print()

print(a3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  3  5]
 [ 7  9 11]]


In [528]:
# Scalar Operations / Arithmetic Operations

a1 = a1 + 5
print(a1.astype(np.int64))

a1 = a1 - 2
print()
print(a1.astype(np.int64))

a1 = a1 * 3                 # Scalar Multiplication
print()
print(a1.astype(np.int64))

a1 = a1 / 4
print()
print(a1.astype(np.int64))

a1 = a1 % 6
print()
print(a1.astype(np.int64))

a1 = a1 ** 3
print()
print(a1.astype(np.int64))

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[12 15 18 21]
 [24 27 30 33]
 [36 39 42 45]]

[[ 3  3  4  5]
 [ 6  6  7  8]
 [ 9  9 10 11]]

[[3 3 4 5]
 [0 0 1 2]
 [3 3 4 5]]

[[ 27  52  91 144]
 [  0   0   3  11]
 [ 27  52  91 144]]


In [529]:
# Relational Operations

a1 == 0
a1 != 0
a1 > 5
a1 < 5
a1 >= 5
a1 <= 5

array([[False, False, False, False],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [530]:
# Vector Operations

a3 = a1+a2
print()
print(a3.astype(np.int64))

a3 = a1-a2
print()
print(a3.astype(np.int64))

a3 = a1*a2
print()
print(a3.astype(np.int64))

a3 = a1/a2
print()
print(a3.astype(np.int64))

a3 = a1**a2
print()
print(a3)

a3 = a1%a2
print()
print(a3.astype(np.int64))


[[ 40  66 106 160]
 [ 17  18  22  31]
 [ 48  74 114 168]]

[[ 14  38  76 128]
 [-17 -17 -15  -8]
 [  6  30  68 120]]

[[ 351  738 1366 2315]
 [   0    7   64  227]
 [ 567 1160 2095 3472]]

[[2 3 6 9]
 [0 0 0 0]
 [1 2 3 6]]

[[4.05255515e+18 1.28621404e+24 2.48063644e+29 3.69527330e+34]
 [0.00000000e+00 1.79187712e-07 1.08943611e+10 1.35192029e+21]
 [1.14456127e+30 7.69243207e+37 1.17940632e+45 7.10345846e+51]]

[[ 1 10  1  0]
 [ 0  0  3 11]
 [ 6  8 22  0]]


In [531]:
# Array Functions

a1 = np.random.random((3, 4))
a1 = np.round(a1*100)
print(a1)

[[58.  3. 70.  5.]
 [67. 54. 76. 20.]
 [12. 29. 86.  3.]]


In [532]:
# max/min/sum/prod

print(f"Max of Vector: {np.max(a1)}")
print(f"Min of Vector: {np.min(a1)}")
print(f"Sum of Vector: {np.sum(a1)}")
print(f"Prod of Vector: {np.prod(a1)}")

Max of Vector: 86.0
Min of Vector: 3.0
Sum of Vector: 483.0
Prod of Vector: 3.0069651378816e+16


In [533]:
# Initalizing Matrix

a = np.arange(1, 41, 2, dtype=int).reshape(4, 5)
print(a)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]]


In [534]:
# array of min's of each row
b = np.min(a, axis=1)
print(b)

# array of min's of each colm
c = np.min(a, axis=0)
print(c)

[ 1 11 21 31]
[1 3 5 7 9]


In [535]:
# array of max's of each row
b = np.max(a, axis=1)
print(b)

# array of max's of each colm
c = np.max(a, axis=0)
print(c)

[ 9 19 29 39]
[31 33 35 37 39]


In [536]:
# array of prod of each row
b = np.prod(a, axis=1)
print(b)

# array of prod of each colm
c = np.prod(a, axis=0)
print(c)

[     945   692835  9454725 51666615]
[  7161  29601  65625 118881 193401]


In [537]:
# array of sum of each row
b = np.sum(a, axis=1)
print(b)

# array of sum of each colm
c = np.sum(a, axis=0)
print(c)

[ 25  75 125 175]
[64 72 80 88 96]


In [538]:
print(f"Mean of a: {np.mean(a)}")
print(f"Median of a: {np.median(a)}")
print(f"Standard Deviation of a: {np.std(a)}")
print(f"Variance of a: {np.var(a)}")

Mean of a: 20.0
Median of a: 20.0
Standard Deviation of a: 11.532562594670797
Variance of a: 133.0


In [539]:
# array of Mean of each row
b = np.mean(a, axis=1)
print(b)

# array of Mean of each colm
b = np.mean(a, axis=0)
print(b)

[ 5. 15. 25. 35.]
[16. 18. 20. 22. 24.]


In [540]:
# array of Median of each row
b = np.median(a, axis=1)
print(b)

# array of Median of each colm
b = np.median(a, axis=0)
print(b)

[ 5. 15. 25. 35.]
[16. 18. 20. 22. 24.]


In [541]:
# array of Std of each row
b = np.std(a, axis=1)
print(b)

# array of Std of each colm
b = np.std(a, axis=0)
print(b)

[2.82842712 2.82842712 2.82842712 2.82842712]
[11.18033989 11.18033989 11.18033989 11.18033989 11.18033989]


In [542]:
# array of Variance of each row
b = np.var(a, axis=1)
print(b)

# array of Variance of each colm
b = np.var(a, axis=0)
print(b)

[8. 8. 8. 8.]
[125. 125. 125. 125. 125.]


In [543]:
# Trignometric Functions

np.sin(a)
# np.cos(a)
# np.tan(a)


array([[ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849],
       [-0.99999021,  0.42016704,  0.65028784, -0.96139749,  0.14987721],
       [ 0.83665564, -0.8462204 , -0.13235175,  0.95637593, -0.66363388],
       [-0.40403765,  0.99991186, -0.42818267, -0.64353813,  0.96379539]])

In [544]:
# dot Product

a = np.arange(1, 11).reshape(2, 5)
b = np.arange(11, 21).reshape(5, 2)

np.dot(a, b)

array([[245, 260],
       [620, 660]])

In [545]:
# log and exponent 

np.log(a)   # log of each element

np.exp(a)   # exponent of each element

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04]])

In [546]:
# round, floor and ceil

a = np.random.random((2, 3))
print(a, "\n")

a = np.round(a*100)
print(a, "\n")

a = np.round(a)
print(a, "\n")

a = np.floor(a)
print(a, "\n")

a = np.ceil(a)
print(a, "\n")

[[0.00346591 0.05482803 0.02006018]
 [0.63992612 0.88124693 0.47563779]] 

[[ 0.  5.  2.]
 [64. 88. 48.]] 

[[ 0.  5.  2.]
 [64. 88. 48.]] 

[[ 0.  5.  2.]
 [64. 88. 48.]] 

[[ 0.  5.  2.]
 [64. 88. 48.]] 



In [555]:
# Indexing and Slicing

a1 = np.arange(10, dtype=int)
a2 = np.arange(12, dtype=int).reshape(3, 4)

print(a1)
print("\n", a2)

[0 1 2 3 4 5 6 7 8 9]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [560]:
print(a1[2::2], "\n")
print(a2[:2,1:], "\n")

[2 4 6 8] 

[[1 2 3]
 [5 6 7]] 

